/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as tenderingFheSol from "./TenderingFHE.sol";
export { Tendering__factory } from "./Tendering__factory";
