/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tenderingFheSol from "./TenderingFHE.sol";
export type { tenderingFheSol };
export type { Tendering } from "./Tendering";
