/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TenderingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createProject"
      | "getProjectStats"
      | "getWinner"
      | "nextProjectId"
      | "placeBid"
      | "projectBids"
      | "projects"
      | "terminateProject"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidPlaced"
      | "ProjectCreated"
      | "ProjectTerminated"
      | "WinnerDeclared"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createProject",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProjectStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextProjectId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "placeBid",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projectBids",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "projects",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "terminateProject",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProject",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProjectStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWinner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextProjectId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "projects", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "terminateProject",
    data: BytesLike
  ): Result;
}

export namespace BidPlacedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    bidder: AddressLike,
    amountETH: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    bidder: string,
    amountETH: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    bidder: string;
    amountETH: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectCreatedEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    creator: AddressLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    creator: string,
    deadline: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    creator: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProjectTerminatedEvent {
  export type InputTuple = [projectId: BigNumberish, terminator: AddressLike];
  export type OutputTuple = [projectId: bigint, terminator: string];
  export interface OutputObject {
    projectId: bigint;
    terminator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerDeclaredEvent {
  export type InputTuple = [
    projectId: BigNumberish,
    winner: AddressLike,
    lowestBidETH: BigNumberish
  ];
  export type OutputTuple = [
    projectId: bigint,
    winner: string,
    lowestBidETH: bigint
  ];
  export interface OutputObject {
    projectId: bigint;
    winner: string;
    lowestBidETH: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Tendering extends BaseContract {
  connect(runner?: ContractRunner | null): Tendering;
  waitForDeployment(): Promise<this>;

  interface: TenderingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProject: TypedContractMethod<
    [_title: string, _description: string, _deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getProjectStats: TypedContractMethod<
    [projectId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        numParticipants: bigint;
        averageBidETH: bigint;
        highestBidETH: bigint;
        lowestBidETH: bigint;
      }
    ],
    "view"
  >;

  getWinner: TypedContractMethod<
    [projectId: BigNumberish],
    [[string, bigint] & { winnerAddress: string; lowestBidETH: bigint }],
    "view"
  >;

  nextProjectId: TypedContractMethod<[], [bigint], "view">;

  placeBid: TypedContractMethod<
    [projectId: BigNumberish, amountETH: BigNumberish],
    [void],
    "nonpayable"
  >;

  projectBids: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        bidder: string;
        amount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  projects: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        title: string;
        description: string;
        deadline: bigint;
        terminated: boolean;
        winner: string;
        winnerDeclared: boolean;
        lowestBid: bigint;
        highestBid: bigint;
        sumBids: bigint;
        numBids: bigint;
        lowestValidBidIndex: bigint;
      }
    ],
    "view"
  >;

  terminateProject: TypedContractMethod<
    [projectId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProject"
  ): TypedContractMethod<
    [_title: string, _description: string, _deadline: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getProjectStats"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [
      [bigint, bigint, bigint, bigint] & {
        numParticipants: bigint;
        averageBidETH: bigint;
        highestBidETH: bigint;
        lowestBidETH: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getWinner"
  ): TypedContractMethod<
    [projectId: BigNumberish],
    [[string, bigint] & { winnerAddress: string; lowestBidETH: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextProjectId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "placeBid"
  ): TypedContractMethod<
    [projectId: BigNumberish, amountETH: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "projectBids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        bidder: string;
        amount: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "projects"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        bigint,
        boolean,
        string,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        creator: string;
        title: string;
        description: string;
        deadline: bigint;
        terminated: boolean;
        winner: string;
        winnerDeclared: boolean;
        lowestBid: bigint;
        highestBid: bigint;
        sumBids: bigint;
        numBids: bigint;
        lowestValidBidIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "terminateProject"
  ): TypedContractMethod<[projectId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BidPlaced"
  ): TypedContractEvent<
    BidPlacedEvent.InputTuple,
    BidPlacedEvent.OutputTuple,
    BidPlacedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectCreated"
  ): TypedContractEvent<
    ProjectCreatedEvent.InputTuple,
    ProjectCreatedEvent.OutputTuple,
    ProjectCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProjectTerminated"
  ): TypedContractEvent<
    ProjectTerminatedEvent.InputTuple,
    ProjectTerminatedEvent.OutputTuple,
    ProjectTerminatedEvent.OutputObject
  >;
  getEvent(
    key: "WinnerDeclared"
  ): TypedContractEvent<
    WinnerDeclaredEvent.InputTuple,
    WinnerDeclaredEvent.OutputTuple,
    WinnerDeclaredEvent.OutputObject
  >;

  filters: {
    "BidPlaced(uint256,address,uint256)": TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;
    BidPlaced: TypedContractEvent<
      BidPlacedEvent.InputTuple,
      BidPlacedEvent.OutputTuple,
      BidPlacedEvent.OutputObject
    >;

    "ProjectCreated(uint256,address,uint256)": TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;
    ProjectCreated: TypedContractEvent<
      ProjectCreatedEvent.InputTuple,
      ProjectCreatedEvent.OutputTuple,
      ProjectCreatedEvent.OutputObject
    >;

    "ProjectTerminated(uint256,address)": TypedContractEvent<
      ProjectTerminatedEvent.InputTuple,
      ProjectTerminatedEvent.OutputTuple,
      ProjectTerminatedEvent.OutputObject
    >;
    ProjectTerminated: TypedContractEvent<
      ProjectTerminatedEvent.InputTuple,
      ProjectTerminatedEvent.OutputTuple,
      ProjectTerminatedEvent.OutputObject
    >;

    "WinnerDeclared(uint256,address,uint256)": TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
    WinnerDeclared: TypedContractEvent<
      WinnerDeclaredEvent.InputTuple,
      WinnerDeclaredEvent.OutputTuple,
      WinnerDeclaredEvent.OutputObject
    >;
  };
}
